### ISSUE TITLE
Request of jade release

### ISSUE THREAD

**Issue by wkentaro** [ros-gbp/view_controller_msgs-release#1]
Could one of the admins work for this?
Our ROS package depend on this package.

**Comment by k-okada** [comment]
any update?

**Comment by k-okada** [comment]
@130s please run

```
bloom-release view_controller_msgs --track jade --rosdistro jade
```

**Comment by 130s** [comment]
I don't believe I have a write access here and honestly didn't even know this package. 
@wjwwood @aleeper Could any of you help make a release?

**Comment by wjwwood** [comment]
I'll release the current version (`0.1.2`) into jade and kinetic. I'll also add @130s to have permissions on this repository in case you need to release in the future (l-turtle). That way you don't have to wait on me if it comes up.

**Comment by wjwwood** [comment]
Jade: https://github.com/ros/rosdistro/pull/12700
Kinetic: https://github.com/ros/rosdistro/pull/12701

**Comment by k-okada** [comment]
Thank You!!!!

## 

◉ Kei Okada
